create table sample_sales_data
(
Rep varchar(15) not null,
Region varchar(8),
Deals_Date date,
Sales_Closed int,
Revenue int,
Customer_Type varchar(10),
Product varchar(10)
)

--- Basic Questions
--Retrieve all columns from the table.
select * from sample_sales_data
--Find records where the Revenue is greater than 50000.
select * from sample_sales_data where revenue > 5000
--Display records where Product is 'Pro' and region is 'North'.
select * from sample_sales_data where region = 'North' and product = 'Pro'
--Find deals closed between '2025-01-01' and '2025-01-31'.
select * from sample_sales_data where date between '2025-01-01' and '2025-01-31'
--Sort the data by Revenue in descending order.
select * from sample_sales_data order by revenue desc
--Count the total number of deals.
select sum(deals_closed) from sample_sales_data
--Show the first 5 records from the table.
select * from sample_sales_data limit 5
--Check for any NULL values in Region.
select * from sample_sales_data where region is null
--List all unique values from the Region column.
select distinct(*) from sample_sales_data
--Find all deals where the Rep is "Anil".
select * from sample_sales_data where sales_rep = 'Anil'
--Show the top 5 entries based on the most recent Deals_Date.
select * from sample_sales_data order by date limit 5
--Find records where Region is NULL.
select * from sample_sales_data where region = 'NULL'

---Intermediate Questions
--Find total revenue generated by each representative.
select sales_rep, sum(revenue) as total_revenue from sample_sales_data group by sales_rep
--Find average revenue per region.
select region, avg(revenue) as average_revenue from sample_sales_data group by region
--List the number of customers of each type (Customer_Type).
select sum(deals_closed) as total_deals, customer_type from sample_sales_data group by customer_type
--Find the top 3 reps by total revenue.
select sales_rep, revenue from sample_sales_data order by revenue desc limit 3
--Show total sales closed per product type.
select sum(deals_closed) as total_sales, product from sample_sales_data group by product 
--Find reps who have closed more than 5 deals in a single day.
select sales_rep, deals_closed from sample_sales_data where deals_closed > 5
--Display the latest deal date for each rep.
SELECT sales_rep, max(date) AS Latest_Deal_Date
FROM sample_sales_data
GROUP BY sales_rep

--Find the revenue per deal for each record (use a computed column).
SELECT sales_rep, Date, deals_closed, revenue,
    CASE 
        WHEN deals_closed > 0 THEN Revenue::DECIMAL / deals_closed
        ELSE NULL
    END AS Revenue_Per_Deal
FROM sample_sales_data
--Group total revenue by product and region.
select region, product, sum(revenue) as total_revenue from sample_sales_data group by region, product

---Advance Questions
--Use a window function to rank reps based on total revenue within each region.
SELECT 
    sales_rep,
    Region,
    Total_Revenue,
    RANK() OVER (PARTITION BY Region ORDER BY Total_Revenue DESC) AS Revenue_Rank
FROM (
    SELECT 
        sales_rep,
        region,
        SUM(revenue) AS Total_Revenue
    FROM sample_sales_data
    GROUP BY sales_rep, region
) AS sub;

--Get the cumulative revenue for each rep sorted by Deals_Date.
SELECT sales_rep, date, revenue, sum(revenue)
OVER (PARTITION BY sales_rep ORDER BY date) AS Cumulative_Revenue
FROM sample_sales_data

--Find the moving average revenue (last 3 entries) for each rep.
SELECT sales_rep, date, revenue, avg(revenue)
OVER (PARTITION BY sales_rep
        ORDER BY date 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS Moving_Avg_Revenue
FROM sample_sales_data

--Identify the top-performing rep (by revenue).
select sales_rep, sum(revenue) as total_revenue from sample_sales_data group by sales_rep limit 1
--Find reps whose total revenue is above the average revenue of all reps.
select sales_rep, sum(revenue) as total_revenue from sample_sales_data group by sales_rep having sum(revenue) > (select avg(revenue) from sample_sales_data)
--Find the second highest revenue generated by each region.
SELECT region, revenue
FROM (SELECT region, revenue,
        DENSE_RANK() OVER (PARTITION BY Region ORDER BY revenue DESC) AS rnk
    FROM sample_sales_data
) ranked
WHERE rnk = 2

--List reps who have sold all types of products.
SELECT sales_rep
FROM sample_sales_data
GROUP BY sales_rep
HAVING COUNT(DISTINCT Product) = (SELECT COUNT(DISTINCT Product) FROM sample_sales_data)

--Write a subquery to find reps who have never sold to a "New" customer.
select sales_rep from sample_sales_data where Customer_Type != 'New'
--Create a view showing region-wise monthly summary (total deals, total revenue).
select region, sum(deals_closed) as total_deals, sum(revenue) as total_revenue from sample_sales_data group by region

